site_name: Block Fortress Documentation
site_url: https://docs.blockfortress.net
site_description: Documentation for Block Fortress.
theme:
  name: material
extra_css:
  - stylesheets/extra.css
  features:
    - tabs
    - instant
    - sections
    - expand
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - attr_list
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  # Do not use '\', it will explode the build system
  - Overview: 'index.md'
  - 'faq.md'
  - 'commands.md'
  - Wand Tool:
    - 'Wand/introduction.md'
    - 'Wand/blocks.md'
