site_name: Block Fortress Documentation
site_url: https://docs.blockfortress.net
site_description: Documentation for Block Fortress.
repo_url: https://github.com/BlackTeam-Corporation/blockfortress-docs
repo_name: blockfortress-docs
extra_css:
  - stylesheets/extra.css
plugins:
  - git-revision-date
  - search
theme:
  name: material
  palette:
    scheme: blockfortress
  custom_dir: overrides
  logo: img/blockfortress.png
  favicon: img/favicon.ico
  features:
    - tabs
    - instant
    - sections
    - expand
#    - toc.integrate
    - header.autohide
    - navigation.tabs
#    - navigation.sections
  icon:
    repo: fontawesome/brands/git-alt

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
    - icon: fontawesome/brands/trello
      link: https://trello.com/b/hvO9dRB1/block-fortress-board   
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/BlockFortressFPS
    - icon: fontawesome/solid/lightbulb
      link: https://feedback.blockfortress.net/b/project 

copyright: 2021 &copy; BlackTeam Corporation<br><small>We are in no way, shape or form affiliated with <a href="https://novalink.games/">Novalink LLC</a>&#8482; or any of its subsidiaries. BLOCKADE 3D&#8482; as well as any other related names, images and assets are registered trademarks of their respective owners.</small><br> 

markdown_extensions:
  - meta
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

nav:
- 'index.md'
- Development:
  - 'development/changelog.md'
  - 'development/feedback.md'
  - 'development/faq.md'
  - 'development/credits.md'
- Getting Started:
  - 'getting_started/commands.md'
  - Tools:
      - 'getting_started/tools/wand.md'
  - Private Servers:
      - 'getting_started/private_servers/introduction.md'
  - Game Modes:
      - 'getting_started/game_modes/battle.md'
      - 'getting_started/game_modes/versus.md'
      - 'getting_started/game_modes/build.md'
      - 'getting_started/game_modes/deathmatch.md'
      - 'getting_started/game_modes/cleaner.md'
  - Maps:
      - 'getting_started/maps/asix.md'
      - 'getting_started/maps/bazaar.md'
      - 'getting_started/maps/bridge.md'
- Support:
    - 'support/guidelines.md'
    - Legal:
        - 'support/legal/terms.md'