site_name: Block Fortress Documentation
theme:
  name: material
extra_css:
  - stylesheets/extra.css
features:
  - navigation.sections
  - navigation.expand
  - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  # Do not use '\', it will explode the build system
  - Overview: 'index.md'
  - 'Commands.md'
  - Wand Tool:
    - 'Wand/GettingStarted.md'
    - 'Wand/BlockList.md'
