site_name: Block Fortress Documentation
site_url: https://docs.blockfortress.net
site_description: Documentation for Block Fortress.
repo_url: https://github.com/BlackTeam-Corporation/blockfortress-docs
repo_name: blockfortress-docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/blockfortress.png
  favicon: img/favicon.ico
  features:
    - tabs
    - instant
    - sections
    - expand
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt
copyright: **BlackTeam Corporation &copy; 2021** &nbsp;*We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with Novalink LLC. Any related names, marks, emblems, images, assets are registered trademarks of their respective owners.*
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - attr_list
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Overview: 'index.md'
  - 'faq.md'
  - 'commands.md'
  - Wand Tool:
    - 'wand/introduction.md'
    - 'wand/blocks.md'
