site_name: Block Fortress Documentation
site_url: https://docs.blockfortress.net
site_description: Documentation for Block Fortress.
repo_url: https://github.com/BlackTeam-Corporation/blockfortress-docs
repo_name: blockfortress-docs
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: img/blockfortress.png
  favicon: img/favicon.ico
  features:
    - tabs
    - instant
    - sections
    - expand
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
    - icon: fontawesome/brands/trello
      link: https://trello.com/b/hvO9dRB1/block-fortress-board   
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/groups/BlockFortressFPS
    - icon: fontawesome/solid/lightbulb
      link: https://feedback.blockfortress.net/b/project 
copyright: 2021 &copy; BlackTeam Corporation<br><small>We are in no way, shape or form affiliated with <a href="https://novalink.games/">Novalink LLC</a>&#8482; or any of its subsidiaries. BLOCKADE 3D&#8482; as well as any other related names, images and assets are registered trademarks of their respective owners.</small> 
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Overview: 'index.md'
  - Information:
    - 'information/terms.md'
    - 'information/guidelines.md'
    - 'information/faq.md'
    - 'information/staff.md'
    - 'information/credits.md'
  - Tools:
    - 'tools/wand.md'
  - Curated Maps:
    - 'maps/asix.md'
    - 'maps/bazaar.md'
    - 'maps/bridge.md'
  - Miscellaneous:
    - 'miscellaneous/commands.md'
